name: Run Playwright tests

on:
  push:
    branches:
      - test
      - test/test
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Change directory to test project
        run: echo "Now in test project folder"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Clear Playwright test results
        run: rm -rf test-results

      - name: Run Playwright tests in Chromium and save output
        id: run_tests
        continue-on-error: true
        run: |
          npx playwright test --project=chromium > result.log 2>&1
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Send Slack notification on test failure
        if: steps.run_tests.outputs.exit_code != '0'
        run: |
          ERROR=$(tail -n 20 result.log | jq -Rs .)
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"🚨 Playwright tests failed on *staging*:\n${ERROR}\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}

        
      - name: Install Allure CLI
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        if: always()
        working-directory: ./company-portal-tests
        run: npx allure generate allure-results -o allure-report --clean

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: company-portal-tests/allure-report

      - name: Upload Allure raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: company-portal-tests/allure-results
