name: Run Playwright tests

on:
  push:
    # branches:
    #   - dev
  pull_request:
    branches:
      - test
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Change directory to test project
        working-directory: ./company-portal-tests
        run: echo "Now in test project folder"

      - name: Install dependencies
        working-directory: ./company-portal-tests
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./company-portal-tests
        run: npx playwright install --with-deps

      - name: Clear Playwright test results
        working-directory: ./company-portal-tests
        run: rm -rf test-results

      - name: Run Playwright tests in Chromium
        working-directory: ./company-portal-tests
        run: npx playwright test --project=chromium
        continue-on-error: true

      # - name: Wait before running Mobile Safari
      #   run: sleep 30

      # - name: Clear Playwright test results
      #   working-directory: ./company-portal-tests
      #   run: rm -rf test-results

      # - name: Run login test on Mobile Safari (iPhone 12)
      #   working-directory: ./company-portal-tests
      #   run: npx playwright test tests/login.spec.ts --project="Mobile Safari"

      - name: Install Allure CLI
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        if: always()
        working-directory: ./company-portal-tests
        run: npx allure generate allure-results -o allure-report --clean

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: company-portal-tests/allure-report

      - name: Upload Allure raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: company-portal-tests/allure-results
